// <auto-generated />
using System;
using Basket.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.Api.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20231215075601_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("basket")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basket.Api.Models.BasketItemModel", b =>
                {
                    b.Property<int>("BasketItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketItemId"));

                    b.Property<int>("BasketId1")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BasketItemId");

                    b.HasIndex("BasketId1");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("BasketItems", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketModel", b =>
                {
                    b.Property<int>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketId"));

                    b.Property<int>("BasketUserId")
                        .HasColumnType("int");

                    b.HasKey("BasketId");

                    b.HasIndex("BasketUserId")
                        .IsUnique();

                    b.ToTable("Baskets", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketUserModel", b =>
                {
                    b.Property<int>("BasketUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketUserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BasketUserId");

                    b.ToTable("BasketUser", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.DiscountModel", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<int>("BasketUserId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.HasIndex("BasketUserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Discounts", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.ProducerModel", b =>
                {
                    b.Property<int>("ProducerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProducerId"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProducerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProducerModel", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("DiscountModelDiscountId")
                        .HasColumnType("int");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("DiscountModelDiscountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProducerId")
                        .IsUnique();

                    b.ToTable("Products", "basket");
                });

            modelBuilder.Entity("CategoryModelProductModel", b =>
                {
                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesCategoryId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("CategoryModelProductModel", "basket");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketItemModel", b =>
                {
                    b.HasOne("Basket.Api.Models.BasketModel", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basket.Api.Models.ProductModel", "Product")
                        .WithOne("BasketItem")
                        .HasForeignKey("Basket.Api.Models.BasketItemModel", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketModel", b =>
                {
                    b.HasOne("Basket.Api.Models.BasketUserModel", "BasketUser")
                        .WithOne("Basket")
                        .HasForeignKey("Basket.Api.Models.BasketModel", "BasketUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketUser");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketUserModel", b =>
                {
                    b.OwnsOne("Framework.Shared.Models.User.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BasketUserModelBasketUserId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BasketUserModelBasketUserId");

                            b1.ToTable("BasketUser", "basket");

                            b1.WithOwner()
                                .HasForeignKey("BasketUserModelBasketUserId");
                        });

                    b.OwnsOne("Framework.Shared.Models.User.Files", "Files", b1 =>
                        {
                            b1.Property<int>("BasketUserModelBasketUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Documents")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Photo")
                                .HasColumnType("int");

                            b1.HasKey("BasketUserModelBasketUserId");

                            b1.ToTable("BasketUser", "basket");

                            b1.WithOwner()
                                .HasForeignKey("BasketUserModelBasketUserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Files")
                        .IsRequired();
                });

            modelBuilder.Entity("Basket.Api.Models.DiscountModel", b =>
                {
                    b.HasOne("Basket.Api.Models.BasketUserModel", "BasketUser")
                        .WithMany("Discounts")
                        .HasForeignKey("BasketUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketUser");
                });

            modelBuilder.Entity("Basket.Api.Models.ProductModel", b =>
                {
                    b.HasOne("Basket.Api.Models.DiscountModel", null)
                        .WithMany("Products")
                        .HasForeignKey("DiscountModelDiscountId");

                    b.HasOne("Basket.Api.Models.ProducerModel", "Producer")
                        .WithOne("Product")
                        .HasForeignKey("Basket.Api.Models.ProductModel", "ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("CategoryModelProductModel", b =>
                {
                    b.HasOne("Basket.Api.Models.CategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basket.Api.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Basket.Api.Models.BasketModel", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("Basket.Api.Models.BasketUserModel", b =>
                {
                    b.Navigation("Basket")
                        .IsRequired();

                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Basket.Api.Models.DiscountModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Basket.Api.Models.ProducerModel", b =>
                {
                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Basket.Api.Models.ProductModel", b =>
                {
                    b.Navigation("BasketItem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
